import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, Compass, CornerDownLeft } from "lucide-react";
import { formatLabel, formatPrice, type SearchResult } from "./search-utils";

function Highlight({ text, query }: { text: string; query: string }) { const term = query.trim().toLowerCase(); const parts = text.split(new RegExp(`(${query.trim().replace(/[.*+?^${}()|[\]\\]/g, "\\$&")})`, "ig")); return <>{parts.map((part, index) => part.toLowerCase() === term ? <mark key={index} className="bg-[#D8B56A]/25 px-0.5 text-inherit">{part}</mark> : part)}</>; }
export function SearchSkeleton() { return <div className="space-y-2" aria-label="Searching catalogue" aria-live="polite">{Array.from({ length: 3 }).map((_, index) => <div key={index} className="flex gap-4 rounded-2xl p-2"><div className="h-20 w-16 shrink-0 animate-pulse rounded-xl bg-white/10 sm:h-24 sm:w-20" /><div className="flex flex-1 flex-col justify-center gap-3"><div className="h-4 w-2/5 animate-pulse rounded bg-white/10" /><div className="h-3 w-1/4 animate-pulse rounded bg-[#D8B56A]/15" /></div></div>)}</div>; }
export default function SearchResults({ results, query, activeIndex, onSelect, onHover }: { results: SearchResult[]; query: string; activeIndex: number; onSelect: () => void; onHover: (index: number) => void; }) {
  if (!results.length) return <motion.div initial={{ opacity: 0, scale: .97 }} animate={{ opacity: 1, scale: 1 }} className="flex min-h-[290px] flex-col items-center justify-center rounded-2xl border border-dashed border-[#D8B56A]/25 bg-white/[.025] px-6 text-center"><div className="mb-4 flex h-14 w-14 items-center justify-center rounded-full border border-[#D8B56A]/35 bg-[#D8B56A]/10 text-[#E6C57A]"><Compass size={25} /></div><h3 className="font-serif text-xl font-light">A rare find is waiting</h3><p className="mt-2 max-w-sm text-sm leading-6 text-white/60">No pieces matched “{query}”. Discover the essentials that define the collection.</p><Link href="/collections" onClick={onSelect} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-full bg-[#E6C57A] px-5 text-sm font-medium text-[#081A35] transition hover:bg-white">Browse collections <ArrowRight size={16} /></Link></motion.div>;
  return <div><p className="mb-3 text-[10px] font-semibold tracking-[.2em] text-[#D8B56A] uppercase">{results.length} curated results</p><div className="space-y-2" role="listbox" aria-label="Search results">{results.map((product, index) => <motion.div key={product.id} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .04 }}><Link href={`/product/${product.id}`} onClick={onSelect} role="option" aria-selected={activeIndex === index} onMouseEnter={() => onHover(index)} className={`group flex items-center gap-3 rounded-2xl p-2 transition sm:gap-4 ${activeIndex === index ? "bg-[#D8B56A]/16 ring-1 ring-[#D8B56A]/35" : "hover:bg-white/7"}`}><div className="relative h-20 w-16 shrink-0 overflow-hidden rounded-xl bg-white/10 sm:h-24 sm:w-20"><Image src={product.image} alt="" fill sizes="80px" className="object-cover transition duration-500 group-hover:scale-105" /></div><div className="min-w-0 flex-1"><p className="truncate text-base font-medium tracking-wide"><Highlight text={product.name} query={query} /></p><p className="mt-1 text-xs tracking-[.12em] text-[#E6C57A] uppercase">{formatLabel(product.collection)} · {formatLabel(product.category)}</p><p className="mt-2 text-sm text-white/70">{formatPrice(product.price)}</p></div><ArrowRight size={19} className="mr-2 text-[#D8B56A] transition-transform group-hover:translate-x-1" /></Link></motion.div>)}</div><p className="mt-4 hidden items-center gap-2 text-xs text-white/40 sm:flex"><CornerDownLeft size={13} /> Use arrow keys to select, then press enter</p></div>;
}
