"use client";

import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowUpRight, Heart } from "lucide-react";

type Product = { id: string; name: string; image: string; hoverImage: string; badge: string; price: number; category?: string; collection?: string; };
export default function ProductCard({ product }: { product: Product }) { return <motion.article whileHover={{ y: -5 }} transition={{ type: "spring", stiffness: 320, damping: 24 }} className="group"><Link href={`/product/${product.id}`} className="block focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#D8B56A] focus-visible:ring-offset-4"><div className="relative aspect-[3/4] overflow-hidden rounded-[2rem] bg-[#e9e7e1]"><Image src={product.image} alt={product.name} fill sizes="(max-width: 640px) 88vw, (max-width: 1024px) 45vw, 25vw" className="object-cover transition duration-700 ease-out group-hover:scale-[1.045]" /><div className="absolute inset-0 bg-gradient-to-t from-[#081A35]/25 via-transparent to-transparent" /><span className="absolute left-3 top-3 rounded-full border border-[#D8B56A]/30 bg-[#081A35]/80 px-3 py-1 text-[10px] font-semibold tracking-[.14em] text-[#E6C57A] uppercase backdrop-blur">{product.badge}</span><button type="button" onClick={(event) => event.preventDefault()} aria-label={`Save ${product.name}`} className="absolute right-3 top-3 flex h-10 w-10 items-center justify-center rounded-full border border-white/25 bg-[#081A35]/70 text-[#E6C57A] backdrop-blur transition hover:scale-105 hover:bg-[#E6C57A] hover:text-[#081A35]"><Heart size={17} /></button><span className="absolute bottom-4 right-4 flex h-10 w-10 items-center justify-center rounded-full bg-white/90 text-[#081A35] opacity-0 shadow-lg transition duration-300 group-hover:opacity-100"><ArrowUpRight size={17} /></span></div><div className="mt-4 flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold tracking-[.16em] text-[#D8B56A] uppercase">{product.collection ?? product.category ?? "TIZA edition"}</p><h3 className="mt-1 text-base font-medium tracking-wide text-[#081A35]">{product.name}</h3></div><p className="shrink-0 pt-4 text-sm text-[#081A35]/70">₹{product.price.toLocaleString("en-IN")}</p></div></Link></motion.article>; }
